# Generated by Django 6.0.1 on 2026-09-07 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Mosety Boat Rides Naivasha', max_length=150)),
                ('legal_name', models.CharField(default='Mosety Boat Rides Naivasha', max_length=150)),
                ('tagline', models.CharField(default='See Naivasha from the water.', max_length=255)),
                ('phone', models.CharField(default='+254 700 000000', max_length=30)),
                ('whatsapp_number', models.CharField(default='+254 700 000000', max_length=30)),
                ('email', models.EmailField(default='info@mosety.co.ke', max_length=254)),
                ('address_text', models.CharField(default='Karagita Public Beach, South Lake Road, Lake Naivasha, Kenya', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=-0.7634, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=36.4258, max_digits=9)),
                ('opening_hours', models.CharField(default='Daily 06:30 - 18:30', max_length=120)),
                ('google_business_url', models.URLField(blank=True, default='')),
                ('directions_url', models.URLField(blank=True, default='https://maps.google.com/?q=-0.763400,36.425800')),
                ('base_url', models.URLField(default='https://mosety.co.ke')),
                ('default_currency', models.CharField(default='KES', max_length=5)),
                ('booking_notice', models.TextField(blank=True, default='Advance booking recommended for morning wildlife tours and weekend sunset cruises.')),
                ('price_verified_at', models.DateField(default=django.utils.timezone.now)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('default_social_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('ga4_measurement_id', models.CharField(blank=True, default='', help_text='e.g. G-XXXXXXXXXX', max_length=50)),
                ('gsc_verification_code', models.CharField(blank=True, default='', max_length=120)),
                ('bing_verification_code', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
