# Generated by Django 6.0.1 on 2026-02-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('GUIDE', 'Guide')], default='CAPTAIN', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('bio', models.TextField(blank=True, help_text='Short bio for the staff profile page.')),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to='staff_qr_codes/')),
                ('total_reviews', models.PositiveIntegerField(default=0, editable=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3)),
            ],
            options={
                'verbose_name': 'Crew Member',
                'verbose_name_plural': 'Crew Members',
                'ordering': ['-average_rating', 'name'],
            },
        ),
    ]
