# Generated by Django 6.0.1 on 2026-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='You can use HTML for formatting.')),
                ('icon_class', models.CharField(help_text="Enter a Font Awesome icon class, e.g., 'fas fa-fish'", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Services will be ordered by this number (lower first).')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
