# Generated by Django 6.0.1 on 2026-02-01 09:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(help_text='Provide a detailed description of the service.'),
        ),
    ]
