# Generated by Django 6.0.1 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/webp/'),
        ),
        migrations.AddField(
            model_name='service',
            name='webp_mobile',
            field=models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='service_images/webp/'),
        ),
    ]
