# Generated by Django 6.0.1 on 2026-09-07 06:38

import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Overrides page title for SEO (50-60 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search engine snippet (140-160 chars)', max_length=160)),
                ('canonical_override', models.CharField(blank=True, help_text='Override canonical URL', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='OpenGraph social title', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='OpenGraph social description', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630 social share preview', null=True, upload_to='seo/og/')),
                ('noindex', models.BooleanField(default=False, help_text='Instruct robots not to index this page')),
                ('nofollow', models.BooleanField(default=False, help_text='Instruct robots not to follow links on this page')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Concise name for chips and selectors', max_length=80)),
                ('summary', models.CharField(help_text='One-sentence differentiator', max_length=255)),
                ('description', models.TextField(help_text='Full editorial description')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='tours/webp/')),
                ('webp_mobile', models.ImageField(blank=True, null=True, upload_to='tours/webp/')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Standard duration in minutes')),
                ('min_guests', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=7)),
                ('is_private', models.BooleanField(default=True, help_text='Available as private charter')),
                ('is_shared', models.BooleanField(default=True, help_text='Available as shared ride')),
                ('departure_location', models.CharField(default='Karagita Public Beach, South Lake Road', max_length=150)),
                ('best_for', models.CharField(default='Wildlife enthusiasts, families, couples', max_length=200)),
                ('highlights', models.TextField(blank=True, help_text='Newline-separated bullet points of what makes this ride special')),
                ('itinerary', models.TextField(blank=True, help_text='Timeline overview of the experience')),
                ('included', models.TextField(default='Full boat charter, licensed local captain, fuel, Coast Guard approved life vests')),
                ('excluded', models.TextField(default='Sanctuary walking fees (if visiting Crescent Island), personal snacks, optional captain gratuities')),
                ('what_to_bring', models.TextField(default='Sunscreen, sun hat, light windbreaker or fleece, camera or smartphone, binoculars')),
                ('safety_notes', models.TextField(default='Mandatory fitted life jackets for all passengers. Captain strictly maintains 30-50m buffer from hippo pods.')),
                ('child_policy', models.TextField(default='Children of all ages welcome. Certified infant and toddler safety vests provided.')),
                ('weather_policy', models.TextField(default='Tours operate in calm conditions and light drizzle. In case of high afternoon winds, rides are rescheduled at zero fee.')),
                ('cancellation_policy', models.TextField(default='Free cancellation or schedule adjustment via WhatsApp up to 2 hours before departure.')),
                ('intent_tag', models.CharField(blank=True, help_text='e.g. wildlife, crescent_island, sunset, family, private, birding', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mosety Tour',
                'verbose_name_plural': 'Mosety Tours',
                'ordering': ['sort_order', 'name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Standard Boat Charter', max_length=100)),
                ('min_guests', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=7)),
                ('pricing_mode', models.CharField(choices=[('PER_BOAT', 'Per Boat Charter'), ('PER_PERSON', 'Per Person')], default='PER_BOAT', max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resident_type', models.CharField(choices=[('ALL', 'All Visitors'), ('RESIDENT', 'Kenyan Resident'), ('NON_RESIDENT', 'Non-Resident')], default='ALL', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Price Tier',
                'verbose_name_plural': 'Price Tiers',
                'ordering': ['sort_order', 'amount_kes'],
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_mode', models.CharField(choices=[('PER_BOOKING', 'Per Booking'), ('PER_PERSON', 'Per Person')], default='PER_BOOKING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eligible_tours', models.ManyToManyField(blank=True, related_name='addons', to='tours.tour')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
