# Generated by Django 6.0.1 on 2026-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerhotel',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main thumbnail image.', null=True, upload_to='hotel_images/'),
        ),
    ]
