# Generated by Django 6.0.1 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_alter_partnerhotel_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_gallery/webp/'),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='webp_mobile',
            field=models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='hotel_gallery/webp/'),
        ),
        migrations.AddField(
            model_name='partnerhotel',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/webp/'),
        ),
        migrations.AddField(
            model_name='partnerhotel',
            name='webp_mobile',
            field=models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='hotel_images/webp/'),
        ),
    ]
