# Generated by Django 6.0.1 on 2026-09-07 06:38

import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='captains/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='captains/webp/')),
                ('webp_mobile', models.ImageField(blank=True, null=True, upload_to='captains/webp/')),
                ('short_bio', models.TextField(help_text='Factual background, local upbringing, navigation credentials')),
                ('years_on_lake', models.PositiveIntegerField(blank=True, help_text='Verified years operating on Lake Naivasha', null=True)),
                ('specialties', models.CharField(help_text='e.g. Hippo behavior, raptor identification, sunrise photography', max_length=200)),
                ('languages', models.CharField(default='English, Swahili', max_length=100)),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mosety Captain',
                'verbose_name_plural': 'Mosety Captains',
                'ordering': ['name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Overrides page title for SEO (50-60 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search engine snippet (140-160 chars)', max_length=160)),
                ('canonical_override', models.CharField(blank=True, help_text='Override canonical URL', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='OpenGraph social title', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='OpenGraph social description', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630 social share preview', null=True, upload_to='seo/og/')),
                ('noindex', models.BooleanField(default=False, help_text='Instruct robots not to index this page')),
                ('nofollow', models.BooleanField(default=False, help_text='Instruct robots not to follow links on this page')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.CharField(help_text='1-2 sentences summarizing the core takeaway', max_length=255)),
                ('body', models.TextField(help_text='Detailed editorial content')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='articles/webp/')),
                ('webp_mobile', models.ImageField(blank=True, null=True, upload_to='articles/webp/')),
                ('author_name', models.CharField(default='Mosety Editorial Team', max_length=100)),
                ('reviewer_name', models.CharField(blank=True, help_text='Verified local captain or wildlife specialist', max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(choices=[('PLANNING', 'Trip Planning'), ('DESTINATION', 'Destination Guide'), ('WILDLIFE', 'Wildlife Entity'), ('JOURNAL', 'Captains Log / Journal'), ('ITINERARY', 'Itinerary')], default='PLANNING', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('related_tours', models.ManyToManyField(blank=True, related_name='guide_articles', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Guide Article',
                'verbose_name_plural': 'Guide Articles',
                'ordering': ['-published_at'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('answer', models.TextField(help_text='Concise, factual answer')),
                ('category', models.CharField(choices=[('General', 'General Questions'), ('Pricing', 'Pricing & Payments'), ('Safety', 'Safety & Standards'), ('Children', 'Children & Families'), ('Logistics', 'Logistics & Arrival'), ('Wildlife', 'Wildlife & Ethics')], default='General', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_verified_at', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('related_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Question & Answer',
                'verbose_name_plural': 'Questions & Answers',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('source', models.CharField(default='Google Review', max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('verified_import', models.BooleanField(default=True)),
                ('permission_status', models.CharField(default='Public Review', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('related_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Guest Testimonial',
                'verbose_name_plural': 'Guest Testimonials',
                'ordering': ['-review_date', '-id'],
            },
        ),
    ]
