# Generated by Django 6.0.1 on 2026-02-02 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_remove_tour_price_per_person_booking_currency_and_more'),
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('testimonial_text', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff_member', models.ForeignKey(blank=True, help_text='Attribute this review to a specific captain or guide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='reputation.staffmember')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='bookings.tour')),
            ],
            options={
                'ordering': ['order', '-date_added'],
            },
        ),
    ]
