# Generated by Django 6.0.1 on 2026-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='customer_country',
            field=models.CharField(blank=True, help_text='e.g. USA, UK, Kenya', max_length=100, null=True),
        ),
    ]
