# Generated by Django 6.0.1 on 2026-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
