# Generated by Django 6.0.1 on 2026-09-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_tour_webp_image_tour_webp_mobile'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('trip_date', models.DateField()),
                ('preferred_time', models.CharField(default='Early Morning (06:30 - 09:00)', help_text='e.g. Early Morning, Mid-Morning, Afternoon, Sunset', max_length=50)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('booking_type', models.CharField(choices=[('PRIVATE', 'Private Boat Charter'), ('SHARED', 'Shared Boat Ride')], default='PRIVATE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requests, photography focus, hotel pickup query')),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('landing_page', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted / WhatsApp Sent'), ('CONFIRMED', 'Confirmed Booking'), ('CANCELLED', 'Cancelled'), ('LOST', 'Lost / No Response')], default='NEW', max_length=20)),
                ('consent_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_leads', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Mosety Booking Lead',
                'verbose_name_plural': 'Mosety Booking Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
