# Generated by Django 6.0.1 on 2026-09-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_normalize_tour_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=255, unique=True)),
                ('new_path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent Redirect'), (302, '302 Temporary Redirect')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Redirect',
                'verbose_name_plural': 'SEO Redirects',
                'ordering': ['old_path'],
            },
        ),
    ]
