# Generated by Django 6.0.1 on 2026-07-23 11:07

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('h1', models.CharField(blank=True, help_text='Override for the H1 tag. Defaults to title.', max_length=200)),
                ('intro_answer', models.TextField(help_text='Plain text, 40-60 words. First visible paragraph. Used for AEO/featured snippets.', max_length=500)),
                ('body', tinymce.models.HTMLField()),
                ('target_keyword', models.CharField(blank=True, max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_pillar', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_indexing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category__sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(max_length=100)),
                ('group_size_label', models.CharField(help_text='e.g. 1-4 people, 5-10 people', max_length=50)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('includes', models.TextField(help_text='What is included in this tier')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide or FontAwesome icon name e.g. fas fa-book', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DownloadAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resources/downloads/')),
                ('file_type', models.CharField(help_text='e.g. PDF, JPEG, etc.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='resources.guidepage')),
            ],
        ),
        migrations.AddField(
            model_name='guidepage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_pages', to='resources.resourcecategory'),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text='Plain text answer, 40-60 words. Used for both display and FAQPage schema.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('guide_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='resources.guidepage')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='resources.resourcecategory')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
